language: python
python:
  - "2.7"

install:
- pip install -r requirements.txt
- pip install -r tests/requirements.txt

script:
- python -m flake8 --max-line-length=120 source
- pytest --cov=source --cov-report term:skip-covered --durations=5 tests
- python -m coveralls
